### ISSUE TITLE
[Question] Image embed references in markdown

### ISSUE THREAD

**Issue by TFWol** [CurtisDS/sd-model-preview-xd#22]
I might be overthinking this, but is it possible to have markdown image embeds show up?

Like:

```
# Some Header
![](./path/to/image1.png)
Description

# Another Header
![](./path/to/image2.png)
Description
```

I haven't been able to make them appear even when trying direct paths like `![](file:///C:/path/to/image.png)`

**Comment by CurtisDS** [comment]
Yes.

For markdown, because of the way it is rendered, the relative path starts at the base automatic1111 directory not where the markdown file is saved. So that's the first thing to note.

Secondly, you have to include `file=` at the start if you are linking to a file on your computer as oppose to a normal URL.

So this should work:

```markdown
![alt text](file=models/Stable-diffusion/image.png)
```

An absolute path would also work, but keep in mind that if the image is outside of the install directory it will give you an error. For those you'd have to either host it and link to the remote host or base64 encode it.

Example of absolute path:

```markdown
![alt text](file=C:\a1111\models\Stable-diffusion\image.png)
```

Just an FYI on html files... because of the way they are handled the base directory for them is different when resolving relative paths. The path is relative to the html file. Because that can get confusing what I do is link it using the web server that automatic1111 runs. So for an image it would be:

```html
<img src="http://127.0.0.1:7860/file=models/Stable-diffusion/image.png">
```

This also works for markdown:

```markdown
![alt text](http://127.0.0.1:7860/file=models/Stable-diffusion/image.png)
```

**Comment by TFWol** [comment]
Thanks, that got things working. I was hitting my head against the wall with the correct syntax/path combination. 

btw, I've been playing around with [pandoc templates](https://pandoc.org/MANUAL.html#option--embed-resources) for a way to mass convert external file refs into local equivalents. Amazing tool if you haven't checked it out.
