### ISSUE TITLE
Revert the order of the images and text

### ISSUE THREAD

**Issue by astroprogs11** [CurtisDS/sd-model-preview-xd#29]
Is there a way to revert the order of the images and text?

I mean, to display the images first, then the content of the .txt file second.

**Comment by CurtisDS** [comment]
There is currently no way to reorder the layout to make the contents of the .txt file appear below the image previews. However there is an easy workaround.

Unlike text previews, markdown and HTML previews appear below the default images. So **just change all your .txt files to .md files**. You shouldn't have to change the contents of the files because markdown should render simple plain text the same as a .txt file for the most part.

**Comment by astroprogs11** [comment]
Very nice, worked like a charm. Thanks a lot!
