### ISSUE TITLE
LyCORIS previews missing after a1111-sd-webui-lycoris auto deactivation

### ISSUE THREAD

**Issue by zethriller** [CurtisDS/sd-model-preview-xd#31]
Checked for extensions updates in A1111 v1.5.2, upon restart i had this message:
```
========================= a1111-sd-webui-lycoris =========================
Starting from stable-diffusion-webui version 1.5.0
a1111-sd-webui-lycoris extension is no longer needed

All its features have been integrated into the native LoRA extension
LyCORIS models can now be used as if there are regular LoRA models

This extension has been automatically deactivated
Please remove this extension
==========================================================================
```

Its removal seem to prevent LyCORIS tab to show up on both the Models Previews tab and the models viewer/selector in txt2img.

Additional note: Lycos are present in the lists, just mixed up with Loras. In the Models Previews tab, order is alphabetical, in the txt2img tab, Lycos always show up by the end of the list and insert the `<lora:xxx:1>` keyword (I don't know if this intended behavior ?)

**Comment by CurtisDS** [comment]
Yes the new version of A1111 now has native support for LyCORIS models and treats them as standard Loras in terms of classification. So they appear in the Lora tab in the extra networks list and in the Lora tab in the model preview extension.

If you have the extra network list open and click on a model card it will load that model or add the tag to the prompt in the case of embeddings, hypernetworks and loras. This is a feature of the automatic1111 UI. Lora tags are formatted with it being <LORA:{{LORA_NAME}}:{{WEIGHT}}>. This should only happen when clicking the model in the extra networks section... if its happening while selecting a model in the Model Previews extension tab let me know as that is not intended and I can't yet replicate that behaviour.

In the extra networks area it will list the models in a "default sort". You can change it to sort by name in the setting beside the search field.
![image](https://github.com/CurtisDS/sd-model-preview-xd/assets/20732674/3a03ba0b-e5e2-470b-9042-3730bbe0b9b3)

There is currently no way to change the sort of the list in the Model Previews tab.

It appears A1111 is intending users to mix their LyCORIS and LORA model folders. From looking at the source code it seems to still support having LyCORIS models in a separate LyCORIS folder but it is labelled as for "backwards compatibility".

If you mix the LyCORIS models in with  your LORA models the "default sort" of the extra networks tab will no longer put all the LyCORIS models at the bottom.

The one issue currently is if you want to keep your LyCORIS models in their separate folder this extension does not look in that folder for previews of Lora models so you will get "No Preview Found" when selecting a LyCORIS model in the LORA tab. For backwards compatibility support I can look at adding the LyCORIS folder as a default folder to also search in for all LORA models. Or you can just move your LyCORIS folder into your LORA folder... this will let you keep the models in separate folders but still let the extension find the preview files because it will look through all the subfolders.
