### ISSUE TITLE
[Feature request] Priority list for the format (.txt, .html, .civitai.info, etc)

### ISSUE THREAD

**Issue by Aryetis** [CurtisDS/sd-model-preview-xd#34]
Hello,

While I like civitai-helper for some of its features. I find their .civitai.info really lacking in terms of useful informations sometimes.
Therefore I would like sd-model-preview-xd to pick my hand crafted .txt over the .civitai.info whenever there is one.

**Comment by CurtisDS** [comment]
The idea of priority only comes into play with HTML files and Civitai Info files. Everything else doesn't have a priority since you can have a .txt, .md, and image files all appearing at once.

The current priority levels are:
HTML > Civitai Info > Everything else (markdown, txt, and images)

If you dont find the civitai info files useful wouldn't it be easier to just delete them, or not download them to begin with? If for some reason you still want the files around... download them and then rename them to something like civitai.ignore.info so the extension doesn't see it. Then your .txt files will appear.

You could also switch to using HTML files instead of txt files as they take priority over civitai info files.

I just don't see the need for a setting to let people change file priorities when you already have pretty much complete control over what files appear.

**Comment by CurtisDS** [comment]
I'm going to close this. If someone can articulate a compelling argument to add this I may reconsider, but right now I am not seeing a need for this feature request.
