### ISSUE TITLE
half screen issue

### ISSUE THREAD

**Issue by cjgausvik** [CurtisDS/sd-model-preview-xd#45]
Hello, 
   I added sd-model-preview-xd to my SD Automatic1111 and the GUI only goes half-way across my web browser. No error messages, and SD still works - it's just not full screen across my browser. Left side is good, but right half is just blank. I can remove the extension and the issue goes away. 

Re-installed Automatic1111, and then sd-model-preview-xd, and recreated the issue. 
When I remove the extension, the problem goes away. 

Running SD Automatic1111 on Windows 11. 32GB RAM on i7-8700K with and RTX 4070. 
Tried this on my normal browser (Firefox - then repeated it on Chrome, and a fresh install of Opera) 

Wondering if you have seen this before, or if there is a fix for it. 
THANKS for all you do!!!

**Comment by CurtisDS** [comment]
can you post what a1111 commit you are on? Also can you post a screenshot of the gui?

**Comment by cjgausvik** [comment]
Thanks for getting back to me!   
yes and no - Happy to give you the commit:   feee37d75f1b168768014e4634dcb156ee649c05

A screen shot is difficult - It's in use right now for a project, and won't be done for a few days so I can't give you the screen shot now - BUT, I saw a picture of someone else's screen that was having the exact same problem (that png is attached).  My issue was identical. 

![half-GUI](https://github.com/CurtisDS/sd-model-preview-xd/assets/148467995/c3bc83f8-c728-44ec-949f-e102de67bf06)
 
 THANKS!

**Comment by CurtisDS** [comment]
The SD Model Preview XD extension does alter the global layout. However, its obviously not supposed to look like that. I am running feee37d75f1b168768014e4634dcb156ee649c05 and don't have this issue. ~~Can you link where you got this screenshot from?~~ nvm [I found it](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/15306)

Also in this screenshot they seem to be using some sort of theme that is altering their install. Do you have a similar theme installed? Its possible that another extension is also altering the CSS of the global layout and causing this.

Also, do you have any `user.css` styles set up in your install?

**Comment by cjgausvik** [comment]
I did have a theme - some dark theme like dracula or something... and that is what I was thinking too - but I removed the theme while I was troubleshooting on my end, so now it is just "Default". Didn't seem to matter if it was installed or not.

**Comment by cjgausvik** [comment]
user.css   no - so much going on in this thing, I never even tried to edit any css files manually.

**Comment by CurtisDS** [comment]
I just did a fresh install and it doesn't have the issue. I also switched to a few different themes and they all worked. Without being able to recreate the problem I cant really help you.

![image](https://github.com/CurtisDS/sd-model-preview-xd/assets/20732674/93d901ca-4500-4931-aac4-2d9d8cfc7931)

**Comment by cjgausvik** [comment]
ok well, thanks for the effort! I appreciate your time.

**Comment by CurtisDS** [comment]
You had said that you did a fresh install so I didn't ask what commit you were on for this extension. But can you confirm your on the latest commit? Because I just remembered that I had seen this exact problem before and fixed it https://github.com/CurtisDS/sd-model-preview-xd/issues/32. But it shouldn't be affecting you if you're running the newest version, that fix is almost a year old now.

If you could post a screen shot of your extensions page it would help me narrow down what version of the extension you have and see if there are any other extensions that might be conflicting.

**Comment by CurtisDS** [comment]
since you havent replied with any new info and because this seems to be an old issue that was already fixed (I cant replicate it on the current version).... I am going to close this again.

**Comment by hugalafutro** [comment]
I have the same issue, it's more like 1/3 of screen used and totally broken and unreadable with default dark theme on sd-webui commit 82a973c04367123ae98bd9abdf80d9eda9b910e2
![image](https://github.com/user-attachments/assets/acd42962-c52d-4686-9a64-3add3e29ca95)

installed extensions:
![image](https://github.com/user-attachments/assets/381473c1-533f-492c-b5b7-bb9c3f6581a7)

Do you want me to open a new issue?

**Comment by CurtisDS** [comment]
The issue OP was talking about was the same issue as #32 and was already fixed. (where the extension limited the width of the entire UI to half the screen)

The issue you are having is different. I dont think its an issue with the extension. Your issue is most likely with your preview file not loading as you are expecting. I can try and help you with it but yea, probably best to move it to a new issue if you dont mind.

It would be helpful if you can post the preview file you are using when you make the new issue. So I can have a look at it.

**Comment by hugalafutro** [comment]
I'm thinking the issue might be elsewhere. I thought this extension dl'd the previews and html, but when I spun a new test instance of sd-webui and only this extension I get `No Preview Found`. If I copy in the model_name.html and .jpg files in from the original install and reload ui I get the broken display, but the thing is those files were downloaded via the civitai browser+ extension. I checked the html and the paths to the images are absolute and if I just doubleclick the html it opens in default browser with all images loaded, but I'm thinking your extension has nothing to do with it, maybe the way the other one saves the html is broken. If you're still interested here's the .html and .jpg files for `openjourney_V4.ckpt`: https://o.o5.ddns.net/sd In any case sorry for bothering you.

What is the "normal" method of downloading the preview files?

**Comment by CurtisDS** [comment]
This extension doesn't download anything on its own. Its up to you to provide the files.

That said, as requested in issue #28 there is support to use `.civitai.info` files as preview files. These can be downloaded using the civitai helper extension linked in that issue. However, as I was later informed... there is apparently a new fork that people [prefer to use](https://github.com/CurtisDS/sd-model-preview-xd/pull/41#issuecomment-1902561733). I'm not sure if the "civitai browser+ extension" is the same thing? or can download the same files? But that is available.

That said... if you have an html file already the extension won't show you the .civitai.info preview because it prioritizes html files. So if you go that route you'd have to remove the html files you already have.

If you want to keep the html files you already have... you will have to update all references to locally stored images and files because based on the file you supplied they are currently all hard coded absolute links when they need to be linked through the gradio file server.

Essentially what this means is you would have to go through and change each of these: 

```html
<link rel="stylesheet" type="text/css" href="T:\AI\stable-diffusion-webui\extensions\sd-civitai-browser-plus\style_html.css">
<img data-sampleimg="true" src="T:\AI\stable-diffusion-webui\models\Stable-diffusion\openjourney_V4_0.jpg">
<img data-sampleimg="true" src="T:\AI\stable-diffusion-webui\models\Stable-diffusion\openjourney_V4_1.jpg"> etc
```

to

```html
<link rel="stylesheet" type="text/css" href="http://127.0.0.1:7860/file=extensions/sd-civitai-browser-plus/style_html.css">
<img data-sampleimg="true" src="http://127.0.0.1:7860/file=models/Stable-diffusion/openjourney_V4_0.jpg">
<img data-sampleimg="true" src="http://127.0.0.1:7860/file=models/Stable-diffusion/openjourney_V4_1.jpg"> etc
```

(notice things have forward slashes instead of back slashes)

This assumes you haven't changed the IP address or port of the webui. You can test that you have the correct link by visiting it (while the webui is running). Open a browser and visit `http://127.0.0.1:7860/file=models/Stable-diffusion/openjourney_V4_0.jpg`. The image should load. That's how you know its correct. Also its worth noting that if you make this change, the html page will not work correctly if you load it without the webui running.

The reason direct links wont work is because of security reasons. Gradio limits you to only be able to access the files it has access to in the webserver that it runs when you turn on the webui.

If you have Notepad++ you can do a batch replace using regular expressions on all the html pages:

Find: `\"T:\\AI\\stable-diffusion-webui\\([^\"]*)\"`
Replace: `"http://127.0.0.1:7860/file=\1"`

![image](https://github.com/user-attachments/assets/1bed0177-f99c-4964-892f-78ef6f7a8a90)

This will turn all the links into: `http://127.0.0.1:7860/file=models\Stable-diffusion\openjourney_V4_0.jpg`. (Notice the incorrect backslashes)... but it should still work even with the mismatched slashes. And this is probably the quickest way to edit all of your HTML files in one go.

**Comment by hugalafutro** [comment]
@CurtisDS  Thanks that worked! The civitai extension I use is https://github.com/BlafKing/sd-civitai-browser-plus, the other one seemed abandoned and broken when I tried it sd-webui crashed with some python dependency error on restart. In this one I have the issue of the send to txt2img button doing nothing sometimes which is why I was looking for alternative.

Thanks for your help even if it wasn't issue with your code, much appreciated!

**Comment by CurtisDS** [comment]
like i said i think this fork https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper is the active one. Idk if its currently broken but the maintainer does seem to be relatively active and responding to issues. If you do go the .civitai.info file route you wont get a  "to txt2img button" but there is a button to copy the meta data to clipboard and then paste that into the positive prompt and load it using the ↙️ button. A few more clicks than a single button but it works lol. (of course it only works if you have meta data)

![image](https://github.com/user-attachments/assets/782dc33e-571d-430f-8523-452657d38a37)

from the .civitai.info preview:
![image](https://github.com/user-attachments/assets/75037b62-e7d0-48e0-b1dc-1ba1e418272a)
