### ISSUE TITLE
Feature request: Tag/category support

### ISSUE THREAD

**Issue by candre23** [CurtisDS/sd-model-preview-xd#6]
This may be a stretch and outside your intended scope, but I would really appreciate some way to filter the model list.  I know I'm probably an outlier with over 250 models in my model directory, but being able to narrow down the list with tags or even simple categories would be a huge benefit.

For tags, perhaps we could create a .tags file for each model with a list of appropriate tags?  It could match to a model by filename or directory, just as the images and .txt files do.  Or if it would be easier, even a single tag file with a line for each model.  Something like `model="learn_v01.safetensors" tags="PORTRAITS, GIRL, WOMAN, LEATHER, PHOTO, ART, SFW, SD15"` or whatever formatting you need.  Then the extension could filter the model list by one or more of those tags.  It would be _amazing_ if it could scrape the tags from civitai, but that's probably asking too much.

If tags are too much of a hassle, I'd happily settle for sorting models based on directory/subdirectory.  Right now I have all the model metadata directories in a ModelPreview directory.  If I could create subdirectories in there for ART, PHOTO, and BOTH, and within each of those have subdirectories for NSFW, SFW, and BOTH, and then sort all the metadata folders into those folders.  If the preview extension could then let me drill down into the appropriate folder and just display those models, that alone would be a big time saver.

PS:  Thank you for adding match-by-directory.  It's been a big help.

**Comment by CurtisDS** [comment]
I'll consider it.

For your folders searching suggestion, something similar is already built into the main a1111 UI for the extra networks tab.

Its not 100% what you want but if you sorted your models into categorized folders (It gets a little more messy if you want a lot of categories and sub categories) then you can go to the extra networks tab and use that search to search for various things.

For example if you had this folder structure:

```
stable-diffusion-webui/
└── models/
    └── Stable-diffusion/
        ├── Work-Safe/
        │   ├── Anime/
        │   │   └── Model1/
        │   │       ├── model1.ckpt
        │   │       ├── model1.preview.png
        │   │       └── info.html
        │   └── Realistic/
        │       └── Model2/
        │           ├── model2.ckpt
        │           ├── model2.preview.png
        │           └── info.html
        └── NSFW/
            ├── Anime/
            │   └── Model3/
            │       ├── model3.ckpt
            │       ├── model3.preview.png
            │       └── info.html
            └── Realistic/
                └── Model4/
                    ├── model4.ckpt
                    ├── model4.preview.png
                    └── info.html
```

![image](https://user-images.githubusercontent.com/20732674/218229088-ae3b03cd-d4e7-45cf-8890-a8b01d905547.png)

These searches would return the following results:

A search of "Anime" would return `model1` and `model3` .
A search of "Work-Safe" would return `model1` and `model2`.
A search of "Work-Safe/Anime" would return `model1`.
etc.

***Note**: you wouldnt be able to use "SFW" as a folder and have it filter correctly because that string is contained in "NSFW" so when you searched for "SFW" both "NSFW" and "SFW" would be returned, which is why I used "Work-Safe" instead in the example.*

And then if you want to see your preview files for a model you've found you could hover over the thumbnail and click on the info button (`ⓘ`) in the thumbnail - [which is a feature I added recently](https://github.com/CurtisDS/sd-model-preview-xd/blob/main/README.md#tips-4) - to link you to the model preview tab with that model selected.
